In [1]:
from NeuroSketch.engine.nn import Linear, Sequential
from NeuroSketch.engine.act import Sigmoid, Softmax, ReLU
from NeuroSketch.utils import DataLoader
from NeuroSketch.losses import BinaryCrossentropyLoss, SparseCategoricalCrossentropyLoss
from NeuroSketch.optims import ADAM, SGD
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('fashion-mnist_test.csv')
df = df.dropna()

In [3]:
df.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,9,8,...,103,87,56,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,34,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,14,53,99,...,0,0,0,0,63,53,31,0,0,0
3,2,0,0,0,0,0,0,0,0,0,...,137,126,140,0,133,224,222,56,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [4]:
X = df.drop(columns=["label"]).to_numpy()
y = df['label'].to_numpy()

In [5]:
y.shape

(10000,)

In [6]:
n = len(y)
x_train, x_test = X[:n // 2], X[n // 2:]
y_train, y_test = y[:n // 2], y[n // 2:]

In [7]:
x_test.shape

(5000, 784)

In [8]:
train = DataLoader(x_train, y_train, shuffle=False)

In [9]:
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
test = DataLoader(x_test, y_test)

In [11]:
model = Sequential(
    Linear(784,10),
    Softmax()
)

In [12]:
criterion = SparseCategoricalCrossentropyLoss(model.layers[-1])

In [13]:
optim = ADAM(model, lr = 0.01)

In [14]:
for epoch in range(100):
    for x_b, y_b in train():
        pred = model(x_b)
        loss = criterion(pred, y_b)
        # print(f"epoch: {epoch} loss: {loss}")
        criterion.backward()
        optim.step()

In [15]:
x_t = test()[0][0]
y_t = test()[0][1]

In [16]:
x_t.shape

(5000, 784)

In [17]:
loss

np.float64(8.254317421884089)

In [18]:
y_pred = model(x_t)
labeled = np.argmax(y_pred, axis=1).reshape(-1, 1)
accuracy = np.mean(labeled == y_t)
print(f"Test accuracy: {accuracy:.4f}")

Test accuracy: 0.0962


In [21]:
labeled

array([[6],
       [6],
       [6],
       ...,
       [6],
       [6],
       [6]], shape=(5000, 1))

In [19]:
print(np.argmax(y_pred[:10], axis=1))
print(y_t[:10])

[6 6 6 6 6 6 6 6 6 6]
[[1]
 [2]
 [4]
 [1]
 [9]
 [2]
 [5]
 [0]
 [9]
 [3]]


In [54]:
np.argmax(y_pred, axis=1).reshape(-1, 1)

array([[9],
       [9],
       [9],
       ...,
       [9],
       [1],
       [9]], shape=(5000, 1))